name: portal_carthage_transfer
description: A Flutter mobile app for Carthage Transfer booking management system.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP client for API calls
  http: ^1.1.0
  
  # State management
  provider: ^6.1.1
  
  # UI components
  cupertino_icons: ^1.0.2
  
  # Local storage
  flutter_secure_storage: ^9.0.0
  
  # JWT handling
  jwt_decoder: ^2.0.1
  
  # Date and time
  intl: ^0.18.1
  
  # URL launcher for WhatsApp
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 